### ISSUE TITLE
send PR to asyncomplete.vim to be included in README.md

### ISSUE THREAD

**Issue by prabirshrestha** [yami-beta/asyncomplete-omni.vim#1]
Just tried it and this works great. Could you send a PR to asyncomplete.vim so that it can be included in README.md?

**Comment by yami-beta** [comment]
Thank you for try and comment. I sent PR to asyncomplete.vim.
https://github.com/prabirshrestha/asyncomplete.vim/pull/22

**Comment by prabirshrestha** [comment]
Merged. Thanks
