### ISSUE TITLE
Example Registration Code in README.md

### ISSUE THREAD

**Issue by s-daveb** [yami-beta/asyncomplete-omni.vim#28]
The line in readme.md that reads:

```\   'show_source_kind': 1 " Add `o` kind label to 'menu' ```

shouldn't have a comment after the `: 1`, or else VIM throws an error about function parameters.

![Screen Shot 2021-04-06 at 1 05 32 PM](https://user-images.githubusercontent.com/2100425/113750441-c6f55000-96d8-11eb-9ecb-d1c739437639.png)

When I add the comma, it then complains that I have an 'missing quote' on that line.

**Comment by yami-beta** [comment]
I fixed README.md.
Thank you.
